server:
  port: 8083

team:
  name: "Web2班"
  leader: "mqxu"
  phone: "15306194436"
  age: ${random.int(1,4)}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

custom:
  qrcode:
    content: "http://www.baidu.com"
